"""miner — Compatibility shim. Implementation lives in mempalace_code.mining.*"""

# ruff: noqa: F401

from .mining.batching import _detect_batch_size, get_batch_size
from .mining.chunkers import (
    CSHARP_BOUNDARY,
    DART_BOUNDARY,
    FSHARP_BOUNDARY,
    GO_BOUNDARY,
    HARD_MAX,
    HCL_BOUNDARY,
    HEADING_MD,
    JAVA_BOUNDARY,
    KOTLIN_BOUNDARY,
    LUA_BOUNDARY,
    MIN_CHUNK,
    PHP_BOUNDARY,
    PY_BOUNDARY,
    RUST_BOUNDARY,
    SCALA_BOUNDARY,
    SWIFT_BOUNDARY,
    TARGET_MAX,
    TARGET_MIN,
    TS_BOUNDARY,
    VBNET_BOUNDARY,
    _chunk_ansible,
    _chunk_ansible_inventory,
    _chunk_ansible_playbook,
    _chunk_ansible_role_tasks,
    _chunk_ansible_role_vars,
    _chunk_dotnet_project_xml,
    _chunk_go_treesitter,
    _chunk_helm,
    _chunk_helm_chart,
    _chunk_helm_template,
    _chunk_helm_values,
    _chunk_k8s_manifest,
    _chunk_python_treesitter,
    _chunk_rust_treesitter,
    _chunk_typescript_treesitter,
    _split_ansible_list_items,
    adaptive_merge_split,
    adaptive_merge_split_sections,
    chunk_adaptive_lines,
    chunk_code,
    chunk_file,
    chunk_prose,
    get_boundary_pattern,
)
from .mining.kg_extract import (
    _CSHARP_TYPE_REL_MATCHERS,
    _KG_EXTRACT_EXTENSIONS,
    _SLN_PROJECT_RE,
    extract_type_relationships,
    parse_dotnet_project_file,
    parse_sln_file,
    parse_xaml_file,
)
from .mining.languages import (
    EXTENSION_LANG_MAP,
    FILENAME_LANG_MAP,
    SHEBANG_PATTERNS,
    _is_ansible_inventory_file,
    _is_ansible_playbook,
    _is_ansible_role_file,
    _is_helm_chart_file,
    _is_k8s_manifest,
    detect_language,
)
from .mining.orchestrator import (
    _bulk_existing_file_hashes,
    _collect_specs_for_file,
    _file_hash,
    _fmt_bytes,
    add_drawer,
    add_drawers_batch,
    file_already_mined,
    get_collection,
    mine,
    process_file,
    status,
)
from .mining.projects import (
    INIT_MARKERS,
    PROJECT_MARKER_GLOBS,
    PROJECT_MARKERS,
    _build_csproj_room_map,
    _detect_sln_wing,
    _normalize_room_name,
    _normalize_wing_name,
    derive_wing_name,
    detect_projects,
    detect_room,
    load_config,
    resolve_wing_for_project,
)
from .mining.scanner import (
    KNOWN_FILENAMES,
    READABLE_EXTENSIONS,
    SKIP_DIRS,
    SKIP_FILENAMES,
    GitignoreMatcher,
    ScanFilterRules,
    _glob_match,
    _is_dotnet_project,
    _subtree_glob_prefix,
    get_scan_filter_rules,
    is_dir_subtree_excluded,
    is_exact_force_include,
    is_force_included,
    is_gitignored,
    is_scan_excluded,
    load_gitignore_matcher,
    normalize_include_paths,
    scan_project,
    should_skip_dir,
)
from .mining.symbols import (
    _ANSIBLE_NON_MODULE_KEYS,
    _LANG_EXTRACT_MAP,
    _TS_IMPORT_RE,
    _extract_ansible_handler_symbol,
    _extract_ansible_play_symbol,
    _extract_ansible_task_symbol,
    _extract_helm_chart_symbol,
    _extract_helm_template_symbol,
    _extract_k8s_symbol,
    extract_symbol,
)
from .treesitter import get_parser
