#!/usr/bin/env python3
"""release_artifact_gate.py — Inspect built wheel and sdist archives.

Checks that both distribution types are present (when required), that archive
members do not contain local-only control artifacts or caches, and delegates
metadata validation to twine check.

Usage:
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist --json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

# Member name prefixes that must not appear in any published archive.
# These are local-only control artifacts generated by the Autopilot pipeline
# and developer tooling; publishing them would leak private state.
FORBIDDEN_MEMBER_PREFIXES: tuple[str, ...] = (
    ".tasks/",
    ".protocols/",
    ".codex-local/",
    "docs/audits/",
    ".verify-state",
    "__pycache__/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".pytest_cache/",
)

AGENT_PLUGIN_REQUIRED_MEMBERS: tuple[str, ...] = (
    "mempalace_code/agent_plugin/plugin.json",
    "mempalace_code/agent_plugin/mcp.json",
    "mempalace_code/agent_plugin/skills/mempalace/SKILL.md",
    "mempalace_code/agent_plugin/schemas/1.0.0/plugin.schema.json",
    "mempalace_code/agent_plugin/schemas/1.0.0/mcp.schema.json",
    "mempalace_code/agent_plugin/schemas/SCHEMA-NOTICE.md",
)

# sdist archives wrap all members under a "<name>-<version>/" prefix.
# Strip that prefix before matching.
SDIST_STRIP_PREFIX = True

PLUGIN_JSON_MEMBER = "mempalace_code/agent_plugin/plugin.json"

# Wheel filenames follow the binary distribution spec: {name}-{version}(-{build})?-...
_WHEEL_VERSION_RE = re.compile(r"^[A-Za-z0-9_.]+-([^-]+)-")


def _strip_sdist_prefix(member: str) -> str:
    """Strip the top-level directory prefix from an sdist member path."""
    parts = member.split("/", 1)
    if len(parts) == 2:
        return parts[1]
    return member


def _check_wheel_members(wheel_path: Path) -> list[str]:
    """Return forbidden member names found in the wheel archive."""
    bad: list[str] = []
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            for name in zf.namelist():
                for prefix in FORBIDDEN_MEMBER_PREFIXES:
                    if name == prefix.rstrip("/") or name.startswith(prefix):
                        bad.append(f"wheel:{name}")
                        break
    except (zipfile.BadZipFile, OSError) as exc:
        bad.append(f"wheel-read-error:{exc}")
    return bad


def _wheel_member_names(wheel_path: Path) -> tuple[set[str], str | None]:
    """Return normalized wheel member names, or a read diagnostic."""
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            return set(zf.namelist()), None
    except (zipfile.BadZipFile, OSError) as exc:
        return set(), f"wheel-read-error:{exc}"


def _check_sdist_members(sdist_path: Path) -> list[str]:
    """Return forbidden member names found in the sdist archive."""
    bad: list[str] = []
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            for member in tf.getmembers():
                name = _strip_sdist_prefix(member.name)
                for prefix in FORBIDDEN_MEMBER_PREFIXES:
                    if name == prefix.rstrip("/") or name.startswith(prefix):
                        bad.append(f"sdist:{member.name}")
                        break
    except (tarfile.TarError, OSError) as exc:
        bad.append(f"sdist-read-error:{exc}")
    return bad


def _sdist_member_names(sdist_path: Path) -> tuple[set[str], str | None]:
    """Return sdist member names after stripping the root prefix, or a read diagnostic."""
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            return {_strip_sdist_prefix(member.name) for member in tf.getmembers()}, None
    except (tarfile.TarError, OSError) as exc:
        return set(), f"sdist-read-error:{exc}"


def _missing_agent_plugin_members(member_names: set[str]) -> list[str]:
    """Return required Agent Plugin package members that are absent."""
    return [member for member in AGENT_PLUGIN_REQUIRED_MEMBERS if member not in member_names]


def _wheel_version_from_filename(wheel_path: Path) -> str | None:
    """Extract the version segment from a wheel filename, per the binary dist spec."""
    match = _WHEEL_VERSION_RE.match(wheel_path.name)
    return match.group(1) if match else None


def _sdist_version_from_filename(sdist_path: Path) -> str | None:
    """Extract the version segment from an sdist filename ({name}-{version}.tar.gz)."""
    stem = sdist_path.name
    if not stem.endswith(".tar.gz"):
        return None
    stem = stem[: -len(".tar.gz")]
    if "-" not in stem:
        return None
    return stem.rsplit("-", 1)[1]


def _read_wheel_plugin_json_version(wheel_path: Path) -> tuple[str | None, str | None]:
    """Return (version, error) from plugin.json inside a wheel archive."""
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            data = json.loads(zf.read(PLUGIN_JSON_MEMBER))
    except KeyError:
        return None, f"{PLUGIN_JSON_MEMBER} not present in wheel"
    except (zipfile.BadZipFile, OSError, json.JSONDecodeError) as exc:
        return None, f"could not read {PLUGIN_JSON_MEMBER} from wheel: {exc}"
    version = data.get("version")
    if version is None:
        return None, f"{PLUGIN_JSON_MEMBER} has no 'version' field"
    return str(version), None


def _read_sdist_plugin_json_version(sdist_path: Path) -> tuple[str | None, str | None]:
    """Return (version, error) from plugin.json inside an sdist archive."""
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            for member in tf.getmembers():
                if _strip_sdist_prefix(member.name) == PLUGIN_JSON_MEMBER:
                    fh = tf.extractfile(member)
                    if fh is None:
                        return None, f"{PLUGIN_JSON_MEMBER} is not a regular file in sdist"
                    data = json.loads(fh.read())
                    version = data.get("version")
                    if version is None:
                        return None, f"{PLUGIN_JSON_MEMBER} has no 'version' field"
                    return str(version), None
        return None, f"{PLUGIN_JSON_MEMBER} not present in sdist"
    except (tarfile.TarError, OSError, json.JSONDecodeError) as exc:
        return None, f"could not read {PLUGIN_JSON_MEMBER} from sdist: {exc}"


def _run_twine_check(dist_dir: Path) -> tuple[bool, str]:
    """Run 'twine check dist/*' and return (ok, output)."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "twine", "check", str(dist_dir / "*")],
            capture_output=True,
            text=True,
            timeout=60,
        )
        # twine check doesn't expand globs; pass actual paths.
        dist_files = list(dist_dir.glob("*.whl")) + list(dist_dir.glob("*.tar.gz"))
        if not dist_files:
            return False, "no distribution files found for twine check"
        result = subprocess.run(
            [sys.executable, "-m", "twine", "check"] + [str(f) for f in dist_files],
            capture_output=True,
            text=True,
            timeout=60,
        )
        ok = result.returncode == 0
        output = (result.stdout + result.stderr).strip()
        return ok, output
    except FileNotFoundError:
        return False, "twine not installed (pip install twine)"
    except subprocess.TimeoutExpired:
        return False, "twine check timed out"


def inspect_dist(
    dist_dir: Path,
    *,
    require_wheel: bool = False,
    require_sdist: bool = False,
    run_twine: bool = True,
) -> dict:
    """Inspect distribution archives in dist_dir.

    Returns a dict with:
        ok: bool
        rows: list of {check, status, detail}
        wheel_found: str|None
        sdist_found: str|None
    """
    rows: list[dict] = []
    ok = True

    wheels = sorted(dist_dir.glob("*.whl"))
    sdists = sorted(dist_dir.glob("*.tar.gz"))

    wheel_path = wheels[0] if wheels else None
    sdist_path = sdists[0] if sdists else None

    # Presence checks.
    if require_wheel:
        if not wheel_path:
            rows.append(
                {"check": "wheel-present", "status": "fail", "detail": "no .whl file found"}
            )
            ok = False
        else:
            rows.append(
                {"check": "wheel-present", "status": "pass", "detail": str(wheel_path.name)}
            )

    if require_sdist:
        if not sdist_path:
            rows.append(
                {"check": "sdist-present", "status": "fail", "detail": "no .tar.gz file found"}
            )
            ok = False
        else:
            rows.append(
                {"check": "sdist-present", "status": "pass", "detail": str(sdist_path.name)}
            )

    # Member inspection.
    if wheel_path:
        bad = _check_wheel_members(wheel_path)
        if bad:
            rows.append(
                {
                    "check": "wheel-members",
                    "status": "fail",
                    "detail": f"forbidden members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "wheel-members", "status": "pass", "detail": str(wheel_path.name)}
            )
        member_names, read_error = _wheel_member_names(wheel_path)
        missing = _missing_agent_plugin_members(member_names)
        if read_error:
            rows.append(
                {"check": "wheel-agent-plugin-members", "status": "fail", "detail": read_error}
            )
            ok = False
        elif missing:
            rows.append(
                {
                    "check": "wheel-agent-plugin-members",
                    "status": "fail",
                    "detail": f"missing required Agent Plugin members: {missing}",
                }
            )
            ok = False
        else:
            rows.append(
                {
                    "check": "wheel-agent-plugin-members",
                    "status": "pass",
                    "detail": "all required Agent Plugin members present",
                }
            )
        if not missing and not read_error:
            filename_version = _wheel_version_from_filename(wheel_path)
            plugin_version, version_error = _read_wheel_plugin_json_version(wheel_path)
            if version_error:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": version_error,
                    }
                )
                ok = False
            elif filename_version is None:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": f"could not parse version from wheel filename: {wheel_path.name}",
                    }
                )
                ok = False
            elif plugin_version != filename_version:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": (
                            f"plugin.json version {plugin_version!r} does not match "
                            f"wheel version {filename_version!r}"
                        ),
                    }
                )
                ok = False
            else:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "pass",
                        "detail": f"plugin.json version matches wheel version {filename_version}",
                    }
                )

    if sdist_path:
        bad = _check_sdist_members(sdist_path)
        if bad:
            rows.append(
                {
                    "check": "sdist-members",
                    "status": "fail",
                    "detail": f"forbidden members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "sdist-members", "status": "pass", "detail": str(sdist_path.name)}
            )
        member_names, read_error = _sdist_member_names(sdist_path)
        missing = _missing_agent_plugin_members(member_names)
        if read_error:
            rows.append(
                {"check": "sdist-agent-plugin-members", "status": "fail", "detail": read_error}
            )
            ok = False
        elif missing:
            rows.append(
                {
                    "check": "sdist-agent-plugin-members",
                    "status": "fail",
                    "detail": f"missing required Agent Plugin members: {missing}",
                }
            )
            ok = False
        else:
            rows.append(
                {
                    "check": "sdist-agent-plugin-members",
                    "status": "pass",
                    "detail": "all required Agent Plugin members present",
                }
            )
        if not missing and not read_error:
            filename_version = _sdist_version_from_filename(sdist_path)
            plugin_version, version_error = _read_sdist_plugin_json_version(sdist_path)
            if version_error:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": version_error,
                    }
                )
                ok = False
            elif filename_version is None:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": f"could not parse version from sdist filename: {sdist_path.name}",
                    }
                )
                ok = False
            elif plugin_version != filename_version:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": (
                            f"plugin.json version {plugin_version!r} does not match "
                            f"sdist version {filename_version!r}"
                        ),
                    }
                )
                ok = False
            else:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "pass",
                        "detail": f"plugin.json version matches sdist version {filename_version}",
                    }
                )

    # Twine check.
    if run_twine and (wheel_path or sdist_path):
        twine_ok, twine_output = _run_twine_check(dist_dir)
        status = "pass" if twine_ok else "fail"
        rows.append({"check": "twine-check", "status": status, "detail": twine_output[:500]})
        if not twine_ok:
            ok = False
    elif run_twine:
        rows.append({"check": "twine-check", "status": "skip", "detail": "no distribution files"})

    return {
        "ok": ok,
        "rows": rows,
        "wheel_found": str(wheel_path.name) if wheel_path else None,
        "sdist_found": str(sdist_path.name) if sdist_path else None,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inspect built wheel and sdist archives for forbidden members."
    )
    parser.add_argument(
        "--dist",
        required=True,
        help="Directory containing built distribution files.",
    )
    parser.add_argument(
        "--require-wheel",
        action="store_true",
        help="Fail if no .whl file is found.",
    )
    parser.add_argument(
        "--require-sdist",
        action="store_true",
        help="Fail if no .tar.gz file is found.",
    )
    parser.add_argument(
        "--no-twine",
        action="store_true",
        help="Skip twine check (useful when twine is not installed).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON.",
    )
    args = parser.parse_args(argv)

    dist_dir = Path(args.dist)
    if not dist_dir.exists():
        msg = f"release-artifact-gate: FAIL — dist directory not found: {dist_dir}"
        if args.json:
            print(json.dumps({"ok": False, "error": str(msg)}))
        else:
            print(msg, file=sys.stderr)
        return 1

    result = inspect_dist(
        dist_dir,
        require_wheel=args.require_wheel,
        require_sdist=args.require_sdist,
        run_twine=not args.no_twine,
    )

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        for row in result["rows"]:
            mark = (
                "PASS"
                if row["status"] == "pass"
                else ("SKIP" if row["status"] == "skip" else "FAIL")
            )
            print(f"  [{mark}] {row['check']}: {row['detail']}")
        if result["ok"]:
            print("release-artifact-gate: OK")
        else:
            print("release-artifact-gate: FAIL", file=sys.stderr)

    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
