#!/usr/bin/env python3
"""release_artifact_gate.py — Inspect built wheel and sdist archives.

Checks that exactly one distribution of each required type is present, that both
archives have the canonical shape their filenames imply, that every shipped file
is a regular file that is either tracked in the repository or an expected
generated member, that the generated metadata set is complete, and delegates
metadata validation to twine check.

Usage:
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist --json
"""

from __future__ import annotations

import argparse
import json
import re
import stat
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

# Member name prefixes that must not appear in any published archive.
# These are local-only control artifacts generated by the Autopilot pipeline
# and developer tooling; publishing them would leak private state.
FORBIDDEN_MEMBER_PREFIXES: tuple[str, ...] = (
    ".tasks/",
    ".protocols/",
    # Agent tooling state holding absolute local paths. Ignored via
    # `.git/info/exclude`, which build backends do not read, so the archive is
    # the only place this is caught.
    ".codex/",
    ".codex-local/",
    "docs/audits/",
    ".verify-state",
    "__pycache__/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".pytest_cache/",
)

# Both archives are the tracked tree plus a small, known set of members the
# build backend generates. Naming the forbidden artifacts one prefix at a time
# only ever catches the leak someone already thought of; requiring every member
# to be tracked closes the class, including paths git hides through
# `.git/info/exclude` (which build backends do not read).
GENERATED_SDIST_MEMBERS: frozenset[str] = frozenset({"PKG-INFO"})

# Derived from a real `python -m build` run, relative to the wheel's canonical
# `.dist-info` root. An exact set, not a prefix and not a ceiling: an extra
# member is either a backend change or an injection, and a missing one means the
# wheel shipped without its license text, its RECORD or its entry points. Both
# directions deserve a human look before they reach PyPI.
GENERATED_DIST_INFO_MEMBERS: frozenset[str] = frozenset(
    {
        "METADATA",
        "RECORD",
        "WHEEL",
        "entry_points.txt",
        "licenses/LICENSE",
        "licenses/NOTICE",
    }
)

# The single import package `[tool.hatch.build.targets.wheel] packages` ships.
WHEEL_PACKAGE_ROOT = "mempalace_code"

# Resolved from this file, not the caller's cwd, so the inventory always
# describes the tree that produced the archive under inspection.
REPO_ROOT = Path(__file__).resolve().parent.parent
GIT_LS_FILES_TIMEOUT = 30

AGENT_PLUGIN_REQUIRED_MEMBERS: tuple[str, ...] = (
    "mempalace_code/agent_plugin/plugin.json",
    "mempalace_code/agent_plugin/mcp.json",
    "mempalace_code/agent_plugin/skills/mempalace/SKILL.md",
    "mempalace_code/agent_plugin/schemas/1.0.0/plugin.schema.json",
    "mempalace_code/agent_plugin/schemas/1.0.0/mcp.schema.json",
    "mempalace_code/agent_plugin/schemas/SCHEMA-NOTICE.md",
)

# sdist archives wrap all members under a "<name>-<version>/" prefix.
# Strip that prefix before matching.
SDIST_STRIP_PREFIX = True

PLUGIN_JSON_MEMBER = "mempalace_code/agent_plugin/plugin.json"

# Wheel filenames follow the binary distribution spec: {name}-{version}(-{build})?-...
_WHEEL_VERSION_RE = re.compile(r"^[A-Za-z0-9_.]+-([^-]+)-")


_WINDOWS_DRIVE_RE = re.compile(r"^[A-Za-z]:")


def _strip_sdist_prefix(member: str) -> str:
    """Strip the top-level directory prefix from an sdist member path."""
    parts = member.split("/", 1)
    if len(parts) == 2:
        return parts[1]
    return member


def _is_unsafe_member_path(name: str) -> bool:
    """True if a member path is absolute, escaping, or not already normalized.

    An unpacker resolves these against the extraction directory, so a member
    that is not a plain relative path can land anywhere on the reader's disk.
    """
    if not name or name != name.strip():
        return True
    if name.startswith("/") or "\\" in name or _WINDOWS_DRIVE_RE.match(name):
        return True
    return any(segment in ("", ".", "..") for segment in name.split("/"))


def _sdist_root_from_filename(sdist_path: Path) -> str | None:
    """Return the single directory every sdist member must live under."""
    name = sdist_path.name
    if not name.endswith(".tar.gz"):
        return None
    root = name[: -len(".tar.gz")]
    return root if "-" in root else None


def _wheel_dist_info_root(wheel_path: Path) -> str | None:
    """Return the canonical `<name>-<version>.dist-info` root for a wheel."""
    parts = wheel_path.name.split("-")
    if len(parts) < 3:
        return None
    return f"{parts[0]}-{parts[1]}.dist-info"


def _is_regular_zip_member(info: zipfile.ZipInfo) -> bool:
    """True if a zip entry's unix mode describes a regular file.

    Zip stores the unix mode in the high half of `external_attr`, and the type
    bits are optional. A real Hatch wheel uses both encodings: S_IFREG on the
    package members and bare permissions with no type bits at all on the
    generated `.dist-info` members, so 0 has to count as regular too. Any other
    type is a FIFO, device, socket, symlink or directory-shaped entry, and an
    unpacker would materialize it as something other than the file the name
    promises.
    """
    file_type = (info.external_attr >> 16) & 0o170000
    return file_type in (0, stat.S_IFREG)


def _is_forbidden_member(name: str) -> bool:
    """True if a member name falls under a forbidden local-artifact prefix."""
    return any(
        name == prefix.rstrip("/") or name.startswith(prefix)
        for prefix in FORBIDDEN_MEMBER_PREFIXES
    )


def tracked_repository_paths(root: Path = REPO_ROOT) -> tuple[frozenset[str], str | None]:
    """Return the repository's tracked paths, or a reason they are unavailable.

    The reason is deliberately redacted to an exception type or exit code: git
    writes absolute local paths to stderr, which is the same class of leakage
    this gate exists to stop.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            capture_output=True,
            timeout=GIT_LS_FILES_TIMEOUT,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return frozenset(), f"git ls-files unavailable ({type(exc).__name__})"
    if proc.returncode != 0:
        return frozenset(), f"git ls-files exited {proc.returncode}"
    paths = frozenset(p for p in proc.stdout.decode("utf-8", "replace").split("\0") if p)
    if not paths:
        return frozenset(), "git ls-files reported no tracked paths"
    return paths, None


def _check_wheel_members(wheel_path: Path) -> list[str]:
    """Return wheel members that do not belong in a published wheel.

    A wheel is the tracked import package plus generated `.dist-info` metadata,
    and nothing else. Checking only against a forbidden-prefix list would still
    ship any locally-excluded file that happens to sit inside the package
    directory, so package members are matched against the tracked inventory and
    metadata members against the exact generated set. Without the inventory the
    rule cannot be evaluated, so the check fails closed.
    """
    tracked, inventory_error = tracked_repository_paths()
    if inventory_error:
        return [f"tracked-source-inventory-unavailable:{inventory_error}"]

    dist_info_root = _wheel_dist_info_root(wheel_path)
    if dist_info_root is None:
        return [f"wheel-unparsable-filename:{wheel_path.name}"]

    bad: list[str] = []
    seen: set[str] = set()
    generated_seen: set[str] = set()
    readable = True
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            for info in zf.infolist():
                name = info.filename
                if info.is_dir():
                    bad.append(f"wheel-directory-entry:{name}")
                elif not _is_regular_zip_member(info):
                    bad.append(f"wheel-non-regular:{name}")
                elif _is_unsafe_member_path(name):
                    bad.append(f"wheel-unsafe-path:{name}")
                elif name in seen:
                    bad.append(f"wheel-duplicate:{name}")
                elif _is_forbidden_member(name):
                    bad.append(f"wheel:{name}")
                elif name.startswith(f"{WHEEL_PACKAGE_ROOT}/"):
                    if name not in tracked:
                        bad.append(f"wheel-untracked:{name}")
                elif name.startswith(f"{dist_info_root}/"):
                    relative = name[len(dist_info_root) + 1 :]
                    if relative in GENERATED_DIST_INFO_MEMBERS:
                        generated_seen.add(relative)
                    else:
                        bad.append(f"wheel-unexpected-dist-info:{name}")
                else:
                    bad.append(f"wheel-foreign-root:{name}")
                seen.add(name)
    except (zipfile.BadZipFile, OSError) as exc:
        readable = False
        bad.append(f"wheel-read-error:{exc}")
    if readable:
        # The other direction of the same equality. Rejecting only extra members
        # would pass a wheel that quietly dropped its license text or its RECORD.
        bad.extend(
            f"wheel-missing-dist-info:{dist_info_root}/{relative}"
            for relative in sorted(GENERATED_DIST_INFO_MEMBERS - generated_seen)
        )
    return bad


def _wheel_member_names(wheel_path: Path) -> tuple[set[str], str | None]:
    """Return normalized wheel member names, or a read diagnostic."""
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            return set(zf.namelist()), None
    except (zipfile.BadZipFile, OSError) as exc:
        return set(), f"wheel-read-error:{exc}"


def _check_sdist_members(sdist_path: Path) -> list[str]:
    """Return sdist members that do not belong in a published sdist.

    Every file should be a plain regular file under the one root the filename
    implies, and should be something git tracks plus the metadata the build
    backend writes. Enumerated prefixes only catch the artifact someone already
    thought of; the tracked-inventory rule closes the class, and the prefixes
    stay as defense in depth. Without the inventory the rule cannot be evaluated
    at all, so the check fails closed.
    """
    tracked, inventory_error = tracked_repository_paths()
    if inventory_error:
        return [f"tracked-source-inventory-unavailable:{inventory_error}"]

    root = _sdist_root_from_filename(sdist_path)
    if root is None:
        return [f"sdist-unparsable-filename:{sdist_path.name}"]

    bad: list[str] = []
    seen: set[str] = set()
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            for member in tf.getmembers():
                name = member.name
                if not member.isfile():
                    # Directories, symlinks, hardlinks and devices all give an
                    # unpacker something to resolve outside the archive.
                    bad.append(f"sdist-non-regular:{name}")
                elif _is_unsafe_member_path(name):
                    bad.append(f"sdist-unsafe-path:{name}")
                elif name in seen:
                    bad.append(f"sdist-duplicate:{name}")
                elif not name.startswith(f"{root}/"):
                    bad.append(f"sdist-foreign-root:{name}")
                elif _is_forbidden_member(name[len(root) + 1 :]):
                    bad.append(f"sdist:{name}")
                elif (
                    name[len(root) + 1 :] not in tracked
                    and name[len(root) + 1 :] not in GENERATED_SDIST_MEMBERS
                ):
                    bad.append(f"sdist-untracked:{name}")
                seen.add(name)
    except (tarfile.TarError, OSError) as exc:
        bad.append(f"sdist-read-error:{exc}")
    return bad


def _sdist_member_names(sdist_path: Path) -> tuple[set[str], str | None]:
    """Return sdist member names after stripping the root prefix, or a read diagnostic."""
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            return {_strip_sdist_prefix(member.name) for member in tf.getmembers()}, None
    except (tarfile.TarError, OSError) as exc:
        return set(), f"sdist-read-error:{exc}"


def _missing_agent_plugin_members(member_names: set[str]) -> list[str]:
    """Return required Agent Plugin package members that are absent."""
    return [member for member in AGENT_PLUGIN_REQUIRED_MEMBERS if member not in member_names]


def _wheel_version_from_filename(wheel_path: Path) -> str | None:
    """Extract the version segment from a wheel filename, per the binary dist spec."""
    match = _WHEEL_VERSION_RE.match(wheel_path.name)
    return match.group(1) if match else None


def _sdist_version_from_filename(sdist_path: Path) -> str | None:
    """Extract the version segment from an sdist filename ({name}-{version}.tar.gz)."""
    stem = sdist_path.name
    if not stem.endswith(".tar.gz"):
        return None
    stem = stem[: -len(".tar.gz")]
    if "-" not in stem:
        return None
    return stem.rsplit("-", 1)[1]


def _read_wheel_plugin_json_version(wheel_path: Path) -> tuple[str | None, str | None]:
    """Return (version, error) from plugin.json inside a wheel archive."""
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            data = json.loads(zf.read(PLUGIN_JSON_MEMBER))
    except KeyError:
        return None, f"{PLUGIN_JSON_MEMBER} not present in wheel"
    except (zipfile.BadZipFile, OSError, json.JSONDecodeError) as exc:
        return None, f"could not read {PLUGIN_JSON_MEMBER} from wheel: {exc}"
    version = data.get("version")
    if version is None:
        return None, f"{PLUGIN_JSON_MEMBER} has no 'version' field"
    return str(version), None


def _read_sdist_plugin_json_version(sdist_path: Path) -> tuple[str | None, str | None]:
    """Return (version, error) from plugin.json inside an sdist archive."""
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            for member in tf.getmembers():
                if _strip_sdist_prefix(member.name) == PLUGIN_JSON_MEMBER:
                    fh = tf.extractfile(member)
                    if fh is None:
                        return None, f"{PLUGIN_JSON_MEMBER} is not a regular file in sdist"
                    data = json.loads(fh.read())
                    version = data.get("version")
                    if version is None:
                        return None, f"{PLUGIN_JSON_MEMBER} has no 'version' field"
                    return str(version), None
        return None, f"{PLUGIN_JSON_MEMBER} not present in sdist"
    except (tarfile.TarError, OSError, json.JSONDecodeError) as exc:
        return None, f"could not read {PLUGIN_JSON_MEMBER} from sdist: {exc}"


def _run_twine_check(dist_dir: Path) -> tuple[bool, str]:
    """Run 'twine check' over the built distributions and return (ok, output)."""
    # twine does not expand globs, so the paths are resolved here.
    dist_files = sorted(dist_dir.glob("*.whl")) + sorted(dist_dir.glob("*.tar.gz"))
    if not dist_files:
        return False, "no distribution files found for twine check"
    try:
        result = subprocess.run(
            [sys.executable, "-m", "twine", "check", *(str(f) for f in dist_files)],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except FileNotFoundError:
        return False, "twine not installed (pip install twine)"
    except subprocess.TimeoutExpired:
        return False, "twine check timed out"
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def _presence_row(kind: str, found: list[Path], suffix: str) -> dict[str, str]:
    """Build the presence row for one distribution type."""
    check = f"{kind}-present"
    if len(found) == 1:
        return {"check": check, "status": "pass", "detail": found[0].name}
    if not found:
        return {"check": check, "status": "fail", "detail": f"no {suffix} file found"}
    return {
        "check": check,
        "status": "fail",
        "detail": f"expected exactly one {suffix}, found {[p.name for p in found]}",
    }


def inspect_dist(
    dist_dir: Path,
    *,
    require_wheel: bool = False,
    require_sdist: bool = False,
    run_twine: bool = True,
) -> dict:
    """Inspect distribution archives in dist_dir.

    Returns a dict with:
        ok: bool
        rows: list of {check, status, detail}
        wheel_found: str|None
        sdist_found: str|None
    """
    rows: list[dict] = []
    ok = True

    wheels = sorted(dist_dir.glob("*.whl"))
    sdists = sorted(dist_dir.glob("*.tar.gz"))

    # Exactly one of each, or nothing is inspected. A dist/ holding two wheels
    # is a stale directory someone forgot to clean: inspecting one of them and
    # reporting "pass" would clear an artifact nobody looked at.
    wheel_path = wheels[0] if len(wheels) == 1 else None
    sdist_path = sdists[0] if len(sdists) == 1 else None

    # Presence checks. Ambiguity is reported even when the type is optional,
    # because there is no safe way to pick which archive the caller meant.
    if require_wheel or len(wheels) > 1:
        rows.append(_presence_row("wheel", wheels, ".whl"))
        ok = ok and len(wheels) == 1

    if require_sdist or len(sdists) > 1:
        rows.append(_presence_row("sdist", sdists, ".tar.gz"))
        ok = ok and len(sdists) == 1

    # Member inspection.
    if wheel_path:
        bad = _check_wheel_members(wheel_path)
        if bad:
            rows.append(
                {
                    "check": "wheel-members",
                    "status": "fail",
                    "detail": f"rejected members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "wheel-members", "status": "pass", "detail": str(wheel_path.name)}
            )
        member_names, read_error = _wheel_member_names(wheel_path)
        missing = _missing_agent_plugin_members(member_names)
        if read_error:
            rows.append(
                {"check": "wheel-agent-plugin-members", "status": "fail", "detail": read_error}
            )
            ok = False
        elif missing:
            rows.append(
                {
                    "check": "wheel-agent-plugin-members",
                    "status": "fail",
                    "detail": f"missing required Agent Plugin members: {missing}",
                }
            )
            ok = False
        else:
            rows.append(
                {
                    "check": "wheel-agent-plugin-members",
                    "status": "pass",
                    "detail": "all required Agent Plugin members present",
                }
            )
        if not missing and not read_error:
            filename_version = _wheel_version_from_filename(wheel_path)
            plugin_version, version_error = _read_wheel_plugin_json_version(wheel_path)
            if version_error:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": version_error,
                    }
                )
                ok = False
            elif filename_version is None:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": f"could not parse version from wheel filename: {wheel_path.name}",
                    }
                )
                ok = False
            elif plugin_version != filename_version:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "fail",
                        "detail": (
                            f"plugin.json version {plugin_version!r} does not match "
                            f"wheel version {filename_version!r}"
                        ),
                    }
                )
                ok = False
            else:
                rows.append(
                    {
                        "check": "wheel-agent-plugin-version",
                        "status": "pass",
                        "detail": f"plugin.json version matches wheel version {filename_version}",
                    }
                )

    if sdist_path:
        bad = _check_sdist_members(sdist_path)
        if bad:
            rows.append(
                {
                    "check": "sdist-members",
                    "status": "fail",
                    "detail": f"rejected members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "sdist-members", "status": "pass", "detail": str(sdist_path.name)}
            )
        member_names, read_error = _sdist_member_names(sdist_path)
        missing = _missing_agent_plugin_members(member_names)
        if read_error:
            rows.append(
                {"check": "sdist-agent-plugin-members", "status": "fail", "detail": read_error}
            )
            ok = False
        elif missing:
            rows.append(
                {
                    "check": "sdist-agent-plugin-members",
                    "status": "fail",
                    "detail": f"missing required Agent Plugin members: {missing}",
                }
            )
            ok = False
        else:
            rows.append(
                {
                    "check": "sdist-agent-plugin-members",
                    "status": "pass",
                    "detail": "all required Agent Plugin members present",
                }
            )
        if not missing and not read_error:
            filename_version = _sdist_version_from_filename(sdist_path)
            plugin_version, version_error = _read_sdist_plugin_json_version(sdist_path)
            if version_error:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": version_error,
                    }
                )
                ok = False
            elif filename_version is None:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": f"could not parse version from sdist filename: {sdist_path.name}",
                    }
                )
                ok = False
            elif plugin_version != filename_version:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "fail",
                        "detail": (
                            f"plugin.json version {plugin_version!r} does not match "
                            f"sdist version {filename_version!r}"
                        ),
                    }
                )
                ok = False
            else:
                rows.append(
                    {
                        "check": "sdist-agent-plugin-version",
                        "status": "pass",
                        "detail": f"plugin.json version matches sdist version {filename_version}",
                    }
                )

    # Twine check.
    if run_twine and (wheel_path or sdist_path):
        twine_ok, twine_output = _run_twine_check(dist_dir)
        status = "pass" if twine_ok else "fail"
        rows.append({"check": "twine-check", "status": status, "detail": twine_output[:500]})
        if not twine_ok:
            ok = False
    elif run_twine:
        rows.append({"check": "twine-check", "status": "skip", "detail": "no distribution files"})

    return {
        "ok": ok,
        "rows": rows,
        "wheel_found": str(wheel_path.name) if wheel_path else None,
        "sdist_found": str(sdist_path.name) if sdist_path else None,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inspect built wheel and sdist archives for members that must not ship."
    )
    parser.add_argument(
        "--dist",
        required=True,
        help="Directory containing built distribution files.",
    )
    parser.add_argument(
        "--require-wheel",
        action="store_true",
        help="Fail if no .whl file is found.",
    )
    parser.add_argument(
        "--require-sdist",
        action="store_true",
        help="Fail if no .tar.gz file is found.",
    )
    parser.add_argument(
        "--no-twine",
        action="store_true",
        help="Skip twine check (useful when twine is not installed).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON.",
    )
    args = parser.parse_args(argv)

    dist_dir = Path(args.dist)
    if not dist_dir.exists():
        msg = f"release-artifact-gate: FAIL — dist directory not found: {dist_dir}"
        if args.json:
            print(json.dumps({"ok": False, "error": str(msg)}))
        else:
            print(msg, file=sys.stderr)
        return 1

    result = inspect_dist(
        dist_dir,
        require_wheel=args.require_wheel,
        require_sdist=args.require_sdist,
        run_twine=not args.no_twine,
    )

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        for row in result["rows"]:
            mark = (
                "PASS"
                if row["status"] == "pass"
                else ("SKIP" if row["status"] == "skip" else "FAIL")
            )
            print(f"  [{mark}] {row['check']}: {row['detail']}")
        if result["ok"]:
            print("release-artifact-gate: OK")
        else:
            print("release-artifact-gate: FAIL", file=sys.stderr)

    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
