#!/usr/bin/env python3
"""release_artifact_gate.py — Inspect built wheel and sdist archives.

Checks that both distribution types are present (when required), that archive
members do not contain local-only control artifacts or caches, and delegates
metadata validation to twine check.

Usage:
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist
    python scripts/release_artifact_gate.py --dist dist --require-wheel --require-sdist --json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

# Member name prefixes that must not appear in any published archive.
# These are local-only control artifacts generated by the Autopilot pipeline
# and developer tooling; publishing them would leak private state.
FORBIDDEN_MEMBER_PREFIXES: tuple[str, ...] = (
    ".tasks/",
    ".protocols/",
    ".codex-local/",
    "docs/audits/",
    ".verify-state",
    "__pycache__/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".pytest_cache/",
)

# sdist archives wrap all members under a "<name>-<version>/" prefix.
# Strip that prefix before matching.
SDIST_STRIP_PREFIX = True


def _strip_sdist_prefix(member: str) -> str:
    """Strip the top-level directory prefix from an sdist member path."""
    parts = member.split("/", 1)
    if len(parts) == 2:
        return parts[1]
    return member


def _check_wheel_members(wheel_path: Path) -> list[str]:
    """Return forbidden member names found in the wheel archive."""
    bad: list[str] = []
    try:
        with zipfile.ZipFile(wheel_path) as zf:
            for name in zf.namelist():
                for prefix in FORBIDDEN_MEMBER_PREFIXES:
                    if name == prefix.rstrip("/") or name.startswith(prefix):
                        bad.append(f"wheel:{name}")
                        break
    except (zipfile.BadZipFile, OSError) as exc:
        bad.append(f"wheel-read-error:{exc}")
    return bad


def _check_sdist_members(sdist_path: Path) -> list[str]:
    """Return forbidden member names found in the sdist archive."""
    bad: list[str] = []
    try:
        with tarfile.open(sdist_path, "r:gz") as tf:
            for member in tf.getmembers():
                name = _strip_sdist_prefix(member.name)
                for prefix in FORBIDDEN_MEMBER_PREFIXES:
                    if name == prefix.rstrip("/") or name.startswith(prefix):
                        bad.append(f"sdist:{member.name}")
                        break
    except (tarfile.TarError, OSError) as exc:
        bad.append(f"sdist-read-error:{exc}")
    return bad


def _run_twine_check(dist_dir: Path) -> tuple[bool, str]:
    """Run 'twine check dist/*' and return (ok, output)."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "twine", "check", str(dist_dir / "*")],
            capture_output=True,
            text=True,
            timeout=60,
        )
        # twine check doesn't expand globs; pass actual paths.
        dist_files = list(dist_dir.glob("*.whl")) + list(dist_dir.glob("*.tar.gz"))
        if not dist_files:
            return False, "no distribution files found for twine check"
        result = subprocess.run(
            [sys.executable, "-m", "twine", "check"] + [str(f) for f in dist_files],
            capture_output=True,
            text=True,
            timeout=60,
        )
        ok = result.returncode == 0
        output = (result.stdout + result.stderr).strip()
        return ok, output
    except FileNotFoundError:
        return False, "twine not installed (pip install twine)"
    except subprocess.TimeoutExpired:
        return False, "twine check timed out"


def inspect_dist(
    dist_dir: Path,
    *,
    require_wheel: bool = False,
    require_sdist: bool = False,
    run_twine: bool = True,
) -> dict:
    """Inspect distribution archives in dist_dir.

    Returns a dict with:
        ok: bool
        rows: list of {check, status, detail}
        wheel_found: str|None
        sdist_found: str|None
    """
    rows: list[dict] = []
    ok = True

    wheels = sorted(dist_dir.glob("*.whl"))
    sdists = sorted(dist_dir.glob("*.tar.gz"))

    wheel_path = wheels[0] if wheels else None
    sdist_path = sdists[0] if sdists else None

    # Presence checks.
    if require_wheel:
        if not wheel_path:
            rows.append(
                {"check": "wheel-present", "status": "fail", "detail": "no .whl file found"}
            )
            ok = False
        else:
            rows.append(
                {"check": "wheel-present", "status": "pass", "detail": str(wheel_path.name)}
            )

    if require_sdist:
        if not sdist_path:
            rows.append(
                {"check": "sdist-present", "status": "fail", "detail": "no .tar.gz file found"}
            )
            ok = False
        else:
            rows.append(
                {"check": "sdist-present", "status": "pass", "detail": str(sdist_path.name)}
            )

    # Member inspection.
    if wheel_path:
        bad = _check_wheel_members(wheel_path)
        if bad:
            rows.append(
                {
                    "check": "wheel-members",
                    "status": "fail",
                    "detail": f"forbidden members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "wheel-members", "status": "pass", "detail": str(wheel_path.name)}
            )

    if sdist_path:
        bad = _check_sdist_members(sdist_path)
        if bad:
            rows.append(
                {
                    "check": "sdist-members",
                    "status": "fail",
                    "detail": f"forbidden members: {bad}",
                }
            )
            ok = False
        else:
            rows.append(
                {"check": "sdist-members", "status": "pass", "detail": str(sdist_path.name)}
            )

    # Twine check.
    if run_twine and (wheel_path or sdist_path):
        twine_ok, twine_output = _run_twine_check(dist_dir)
        status = "pass" if twine_ok else "fail"
        rows.append({"check": "twine-check", "status": status, "detail": twine_output[:500]})
        if not twine_ok:
            ok = False
    elif run_twine:
        rows.append({"check": "twine-check", "status": "skip", "detail": "no distribution files"})

    return {
        "ok": ok,
        "rows": rows,
        "wheel_found": str(wheel_path.name) if wheel_path else None,
        "sdist_found": str(sdist_path.name) if sdist_path else None,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inspect built wheel and sdist archives for forbidden members."
    )
    parser.add_argument(
        "--dist",
        required=True,
        help="Directory containing built distribution files.",
    )
    parser.add_argument(
        "--require-wheel",
        action="store_true",
        help="Fail if no .whl file is found.",
    )
    parser.add_argument(
        "--require-sdist",
        action="store_true",
        help="Fail if no .tar.gz file is found.",
    )
    parser.add_argument(
        "--no-twine",
        action="store_true",
        help="Skip twine check (useful when twine is not installed).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON.",
    )
    args = parser.parse_args(argv)

    dist_dir = Path(args.dist)
    if not dist_dir.exists():
        msg = f"release-artifact-gate: FAIL — dist directory not found: {dist_dir}"
        if args.json:
            print(json.dumps({"ok": False, "error": str(msg)}))
        else:
            print(msg, file=sys.stderr)
        return 1

    result = inspect_dist(
        dist_dir,
        require_wheel=args.require_wheel,
        require_sdist=args.require_sdist,
        run_twine=not args.no_twine,
    )

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        for row in result["rows"]:
            mark = (
                "PASS"
                if row["status"] == "pass"
                else ("SKIP" if row["status"] == "skip" else "FAIL")
            )
            print(f"  [{mark}] {row['check']}: {row['detail']}")
        if result["ok"]:
            print("release-artifact-gate: OK")
        else:
            print("release-artifact-gate: FAIL", file=sys.stderr)

    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
